version: '3.7'
services:
  postgres-PrFm:
    image: postgres
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/mysql
    environment:
      - POSTGRES_DB=Postgre
      - POSTGRES_USER=scriper
      - POSTGRES_PASSWORD=123